// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKb4BCyGDkKSchOx7-j1el7pTVy40iLOs',
    appId: '1:892483646621:web:3468f88fc67005037dd074',
    messagingSenderId: '892483646621',
    projectId: 'quickplate-c4028',
    authDomain: 'quickplate-c4028.firebaseapp.com',
    storageBucket: 'quickplate-c4028.firebasestorage.app',
    measurementId: 'G-LY85XRV8KY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYcGpwyYlWnc283tFMaOFNNJDX54kN2GM',
    appId: '1:892483646621:android:b23f9a172bd5c5b97dd074',
    messagingSenderId: '892483646621',
    projectId: 'quickplate-c4028',
    storageBucket: 'quickplate-c4028.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2W_T2YtmpCNWXT6SOUZJn_lo6K9CSvrI',
    appId: '1:892483646621:ios:1c84b2f43fcb70b27dd074',
    messagingSenderId: '892483646621',
    projectId: 'quickplate-c4028',
    storageBucket: 'quickplate-c4028.firebasestorage.app',
    iosBundleId: 'com.example.quickPlate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2W_T2YtmpCNWXT6SOUZJn_lo6K9CSvrI',
    appId: '1:892483646621:ios:1c84b2f43fcb70b27dd074',
    messagingSenderId: '892483646621',
    projectId: 'quickplate-c4028',
    storageBucket: 'quickplate-c4028.firebasestorage.app',
    iosBundleId: 'com.example.quickPlate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKb4BCyGDkKSchOx7-j1el7pTVy40iLOs',
    appId: '1:892483646621:web:250f867725f5fc717dd074',
    messagingSenderId: '892483646621',
    projectId: 'quickplate-c4028',
    authDomain: 'quickplate-c4028.firebaseapp.com',
    storageBucket: 'quickplate-c4028.firebasestorage.app',
    measurementId: 'G-F37Z7JCND5',
  );
}
