name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  analyze_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version-file: '.fvmrc'
          cache: true

      - name: Create Dummy .env
        run: touch .env

      - name: Install Dependencies
        run: flutter pub get

      - name: Verify Formatting
        run: dart format --output=none --set-exit-if-changed lib/

      - name: Analyze Project Code
        run: flutter analyze

      - name: Run Unit Tests
        run: flutter test
